name: Python CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v3
        with:
         python-version: '3.x'
      - name: Install dependencies
        run: |
         pip install poetry
         poetry install
      - name: Run linter and pytest
        run: |
          make test
          make lint
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
         CC_TEST_REPORTER_ID: bfa36b03f0a5d0f6122b291d46bb6e0e575c94f956a3629431126b30db6c8bff
        with:
           coverageCommand: poetry run pytest --cov=gendiff --cov-report xml
           debug: true
